### ISSUE TITLE
"who"method is not working.... 

### ISSUE THREAD

**Issue by MedAziz11** [tucnakomet1/Python-Who-Is-On-My-WiFi#4]
>>> import who_is_on_my_wifi as wifi
>>> wifi.who()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\GitHub\WiFi_Hub\env\lib\site-packages\who_is_on_my_wifi.py", line 126, in who
    dev = device()
  File "D:\GitHub\WiFi_Hub\env\lib\site-packages\who_is_on_my_wifi.py", line 313, in device
    DNS1 = out[indx[1]+13]
IndexError: list index out of range
>>>

**Comment by tucnakomet1** [comment]
Thank you for reporting a bug.

I am currently preparing a new update (Version 1.2.0), where all bugs will be fixed and the module will also support MacOS.

Sometime next week (21. - 27.9) a new version will be out.

Thanks again for reporting the bug, it will be fixed.
