### ISSUE TITLE
only seeing my own device 

### ISSUE THREAD

**Issue by sophondetector** [tucnakomet1/Python-Who-Is-On-My-WiFi#9]
```sh
% sudo wiom -w

IP Address:  10.0.0.35
Mac Address:  XXXX
Device:  LENOVO LNVNB161216 (Your device)
```
or if i run 
```sh
% sudo python
>>> import who_is_on_my_wifi
>>> who_is_on_my_wifi.who()
[['IP Address:', '10.0.0.35', 'Mac Address:', 'XXXX', 'Device:', 'LENOVO LNVNB161216 (Your device)']]
```
i have many devices; ipad, tv, etc, i remember this working when i first downloaded it; i have no idea why it would be malfunctioning now
i installed from source with pip; i am running 3.8.5 in a venv

**Comment by tucnakomet1** [comment]
Hello, 
thanks for your report.

It sometimes run correctly and sometimes not, that's the reason why I decided to make new version with different module - no `Nmap` but `Scapy` - which has in my tests much better results. Sadly said, I can't help you, you can just try to run it again and again... <br/>
I know about this problem and I'm working on its repair.
In a 3 weeks there will be another, better `who-is-on-my-wifi` also with more features so you can look forward to it. *(it's almost done, on Linux and Windows it runs perfectly)*. 

I hope you're not gonna give it up and I hope you'll be more satisfied with newer version.<br/>
**I apologize** for inconvenience and **thank you** again.

**Comment by sophondetector** [comment]
looking forward to seeing what you come up with; i am learning scapy and am interested in contributing

**Comment by tucnakomet1** [comment]
You can contact me via my email [tucnakomet@gmail.com](mailto:tucnakomet@gmail.com) if you want to contribute *(or ask anything)*.

**Comment by ehtesham-ali** [comment]
Hi, I'm also having the same issue with the program only showing 1 device (mine). Has this issue been resolved yet?

**Comment by tucnakomet1** [comment]
Hello,
As I said, my module depends on another module - `Scapy` - and `Scapy` scans the network, so what `Scapy` shows, shows also `wiom`. 

You'll get better results if you run `wiom` for at least 60 seconds ( `sudo wiom -w -t 60` ), but if it only shows your device, it's probably not just my fault, but maybe a weird WiFi configuration.

Just to be sure, does it only show your device? Not even the router? No error message?

Thanks, I'll look into it!

**Comment by ehtesham-ali** [comment]
Hello,
I ran this script in VS Code running Python 3.9.6 (64 bit):
````
from who_is_on_my_wifi import *

WHO = who() # who(n)
for j in range(0, len(WHO)):
	comm = f"\n{WHO[j][0]} {WHO[j][1]}\n{WHO[j][2]} {WHO[j][3]}\n{WHO[j][4]} {WHO[j][5]}\n"
	print(comm)
````

...and got this error message (although I technically did get a result back):
````
ERROR: --- Error sending packets
Traceback (most recent call last):
  File "C:\Users\ehtes\AppData\Local\Programs\Python\Python39\lib\site-packages\scapy\utils.py", line 638, in atol
    ip = inet_aton(x)
OSError: illegal IP address string passed to inet_aton

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\ehtes\AppData\Local\Programs\Python\Python39\lib\site-packages\scapy\sendrecv.py", line 245, in _sndrcv_snd
    self.pks.send(p)
  File "C:\Users\ehtes\AppData\Local\Programs\Python\Python39\lib\site-packages\scapy\arch\libpcap.py", line 433, in send
    sx = raw(x)
  File "C:\Users\ehtes\AppData\Local\Programs\Python\Python39\lib\site-packages\scapy\compat.py", line 279, in raw
    return bytes(x)
  File "C:\Users\ehtes\AppData\Local\Programs\Python\Python39\lib\site-packages\scapy\packet.py", line 564, in __bytes__
    return self.build()
  File "C:\Users\ehtes\AppData\Local\Programs\Python\Python39\lib\site-packages\scapy\packet.py", line 695, in build
    p = self.do_build()
  File "C:\Users\ehtes\AppData\Local\Programs\Python\Python39\lib\site-packages\scapy\packet.py", line 678, in do_build
    pay = self.do_build_payload()
  File "C:\Users\ehtes\AppData\Local\Programs\Python\Python39\lib\site-packages\scapy\packet.py", line 664, in do_build_payload
    return self.payload.do_build()
  File "C:\Users\ehtes\AppData\Local\Programs\Python\Python39\lib\site-packages\scapy\packet.py", line 675, in do_build
    pkt = self.self_build()
  File "C:\Users\ehtes\AppData\Local\Programs\Python\Python39\lib\site-packages\scapy\packet.py", line 654, in self_build
    p = f.addfield(self, p, val)
  File "C:\Users\ehtes\AppData\Local\Programs\Python\Python39\lib\site-packages\scapy\fields.py", line 529, in addfield
    return fld.addfield(pkt, s, val)
  File "C:\Users\ehtes\AppData\Local\Programs\Python\Python39\lib\site-packages\scapy\fields.py", line 236, in addfield
    return s + self.struct.pack(self.i2m(pkt, val))
  File "C:\Users\ehtes\AppData\Local\Programs\Python\Python39\lib\site-packages\scapy\fields.py", line 833, in i2m
    x = self.__findaddr(pkt)
  File "C:\Users\ehtes\AppData\Local\Programs\Python\Python39\lib\site-packages\scapy\fields.py", line 828, in __findaddr
    return conf.route.route(dst)[1]
  File "C:\Users\ehtes\AppData\Local\Programs\Python\Python39\lib\site-packages\scapy\route.py", line 176, in route
    atol_dst = atol(_dst)
  File "C:\Users\ehtes\AppData\Local\Programs\Python\Python39\lib\site-packages\scapy\utils.py", line 640, in atol
    ip = inet_aton(socket.gethostbyname(x))
socket.gaierror: [Errno 11001] getaddrinfo failed
ERROR: --- Error sending packets
Traceback (most recent call last):
  File "C:\Users\ehtes\AppData\Local\Programs\Python\Python39\lib\site-packages\scapy\utils.py", line 638, in atol
    ip = inet_aton(x)
OSError: illegal IP address string passed to inet_aton

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\ehtes\AppData\Local\Programs\Python\Python39\lib\site-packages\scapy\sendrecv.py", line 245, in _sndrcv_snd
    self.pks.send(p)
  File "C:\Users\ehtes\AppData\Local\Programs\Python\Python39\lib\site-packages\scapy\arch\libpcap.py", line 433, in send
    sx = raw(x)
  File "C:\Users\ehtes\AppData\Local\Programs\Python\Python39\lib\site-packages\scapy\compat.py", line 279, in raw
    return bytes(x)
  File "C:\Users\ehtes\AppData\Local\Programs\Python\Python39\lib\site-packages\scapy\packet.py", line 564, in __bytes__
    return self.build()
  File "C:\Users\ehtes\AppData\Local\Programs\Python\Python39\lib\site-packages\scapy\packet.py", line 695, in build
    p = self.do_build()
  File "C:\Users\ehtes\AppData\Local\Programs\Python\Python39\lib\site-packages\scapy\packet.py", line 678, in do_build
    pay = self.do_build_payload()
  File "C:\Users\ehtes\AppData\Local\Programs\Python\Python39\lib\site-packages\scapy\packet.py", line 664, in do_build_payload
    return self.payload.do_build()
  File "C:\Users\ehtes\AppData\Local\Programs\Python\Python39\lib\site-packages\scapy\packet.py", line 675, in do_build
    pkt = self.self_build()
  File "C:\Users\ehtes\AppData\Local\Programs\Python\Python39\lib\site-packages\scapy\packet.py", line 654, in self_build
    p = f.addfield(self, p, val)
  File "C:\Users\ehtes\AppData\Local\Programs\Python\Python39\lib\site-packages\scapy\fields.py", line 529, in addfield
    return fld.addfield(pkt, s, val)
  File "C:\Users\ehtes\AppData\Local\Programs\Python\Python39\lib\site-packages\scapy\fields.py", line 236, in addfield
    return s + self.struct.pack(self.i2m(pkt, val))
  File "C:\Users\ehtes\AppData\Local\Programs\Python\Python39\lib\site-packages\scapy\fields.py", line 833, in i2m
    x = self.__findaddr(pkt)
  File "C:\Users\ehtes\AppData\Local\Programs\Python\Python39\lib\site-packages\scapy\fields.py", line 828, in __findaddr
    return conf.route.route(dst)[1]
  File "C:\Users\ehtes\AppData\Local\Programs\Python\Python39\lib\site-packages\scapy\route.py", line 176, in route
    atol_dst = atol(_dst)
  File "C:\Users\ehtes\AppData\Local\Programs\Python\Python39\lib\site-packages\scapy\utils.py", line 640, in atol
    ip = inet_aton(socket.gethostbyname(x))
socket.gaierror: [Errno 11001] getaddrinfo failed
ERROR: more --- Error sending packets
Traceback (most recent call last):
  File "C:\Users\ehtes\AppData\Local\Programs\Python\Python39\lib\site-packages\scapy\utils.py", line 638, in atol
    ip = inet_aton(x)
OSError: illegal IP address string passed to inet_aton

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\ehtes\AppData\Local\Programs\Python\Python39\lib\site-packages\scapy\sendrecv.py", line 245, in _sndrcv_snd
    self.pks.send(p)
  File "C:\Users\ehtes\AppData\Local\Programs\Python\Python39\lib\site-packages\scapy\arch\libpcap.py", line 433, in send
    sx = raw(x)
  File "C:\Users\ehtes\AppData\Local\Programs\Python\Python39\lib\site-packages\scapy\compat.py", line 279, in raw
    return bytes(x)
  File "C:\Users\ehtes\AppData\Local\Programs\Python\Python39\lib\site-packages\scapy\packet.py", line 564, in __bytes__
    return self.build()
  File "C:\Users\ehtes\AppData\Local\Programs\Python\Python39\lib\site-packages\scapy\packet.py", line 695, in build
    p = self.do_build()
  File "C:\Users\ehtes\AppData\Local\Programs\Python\Python39\lib\site-packages\scapy\packet.py", line 678, in do_build
    pay = self.do_build_payload()
  File "C:\Users\ehtes\AppData\Local\Programs\Python\Python39\lib\site-packages\scapy\packet.py", line 664, in do_build_payload
    return self.payload.do_build()
  File "C:\Users\ehtes\AppData\Local\Programs\Python\Python39\lib\site-packages\scapy\packet.py", line 675, in do_build
    pkt = self.self_build()
  File "C:\Users\ehtes\AppData\Local\Programs\Python\Python39\lib\site-packages\scapy\packet.py", line 654, in self_build
    p = f.addfield(self, p, val)
  File "C:\Users\ehtes\AppData\Local\Programs\Python\Python39\lib\site-packages\scapy\fields.py", line 529, in addfield
    return fld.addfield(pkt, s, val)
  File "C:\Users\ehtes\AppData\Local\Programs\Python\Python39\lib\site-packages\scapy\fields.py", line 236, in addfield
    return s + self.struct.pack(self.i2m(pkt, val))
  File "C:\Users\ehtes\AppData\Local\Programs\Python\Python39\lib\site-packages\scapy\fields.py", line 833, in i2m
    x = self.__findaddr(pkt)
  File "C:\Users\ehtes\AppData\Local\Programs\Python\Python39\lib\site-packages\scapy\fields.py", line 828, in __findaddr
    return conf.route.route(dst)[1]
  File "C:\Users\ehtes\AppData\Local\Programs\Python\Python39\lib\site-packages\scapy\route.py", line 176, in route
    atol_dst = atol(_dst)
  File "C:\Users\ehtes\AppData\Local\Programs\Python\Python39\lib\site-packages\scapy\utils.py", line 640, in atol
    ip = inet_aton(socket.gethostbyname(x))
socket.gaierror: [Errno 11001] getaddrinfo failed
ERROR: --- Error sending packets
Traceback (most recent call last):
  File "C:\Users\ehtes\AppData\Local\Programs\Python\Python39\lib\site-packages\scapy\utils.py", line 638, in atol
    ip = inet_aton(x)
OSError: illegal IP address string passed to inet_aton

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\ehtes\AppData\Local\Programs\Python\Python39\lib\site-packages\scapy\sendrecv.py", line 245, in _sndrcv_snd
    self.pks.send(p)
  File "C:\Users\ehtes\AppData\Local\Programs\Python\Python39\lib\site-packages\scapy\arch\libpcap.py", line 433, in send
    sx = raw(x)
  File "C:\Users\ehtes\AppData\Local\Programs\Python\Python39\lib\site-packages\scapy\compat.py", line 279, in raw
    return bytes(x)
  File "C:\Users\ehtes\AppData\Local\Programs\Python\Python39\lib\site-packages\scapy\packet.py", line 564, in __bytes__
    return self.build()
  File "C:\Users\ehtes\AppData\Local\Programs\Python\Python39\lib\site-packages\scapy\packet.py", line 695, in build
    p = self.do_build()
  File "C:\Users\ehtes\AppData\Local\Programs\Python\Python39\lib\site-packages\scapy\packet.py", line 678, in do_build
    pay = self.do_build_payload()
  File "C:\Users\ehtes\AppData\Local\Programs\Python\Python39\lib\site-packages\scapy\packet.py", line 664, in do_build_payload
    return self.payload.do_build()
  File "C:\Users\ehtes\AppData\Local\Programs\Python\Python39\lib\site-packages\scapy\packet.py", line 675, in do_build
    pkt = self.self_build()
  File "C:\Users\ehtes\AppData\Local\Programs\Python\Python39\lib\site-packages\scapy\packet.py", line 654, in self_build
    p = f.addfield(self, p, val)
  File "C:\Users\ehtes\AppData\Local\Programs\Python\Python39\lib\site-packages\scapy\fields.py", line 529, in addfield
    return fld.addfield(pkt, s, val)
  File "C:\Users\ehtes\AppData\Local\Programs\Python\Python39\lib\site-packages\scapy\fields.py", line 236, in addfield
    return s + self.struct.pack(self.i2m(pkt, val))
  File "C:\Users\ehtes\AppData\Local\Programs\Python\Python39\lib\site-packages\scapy\fields.py", line 833, in i2m
    x = self.__findaddr(pkt)
  File "C:\Users\ehtes\AppData\Local\Programs\Python\Python39\lib\site-packages\scapy\fields.py", line 828, in __findaddr
    return conf.route.route(dst)[1]
  File "C:\Users\ehtes\AppData\Local\Programs\Python\Python39\lib\site-packages\scapy\route.py", line 176, in route
    atol_dst = atol(_dst)
  File "C:\Users\ehtes\AppData\Local\Programs\Python\Python39\lib\site-packages\scapy\utils.py", line 640, in atol
    ip = inet_aton(socket.gethostbyname(x))
socket.gaierror: [Errno 11001] getaddrinfo failed

IP Address: (censored)
Mac Address: (censored)
Device: Dell Inc. G5 5000 (Your device)
````

P.S What is `wiom`? I'm a relatively new programmer...

Thanks!

**Comment by tucnakomet1** [comment]
I'm not sure, but this error could mean that you didn't run it as an administrator.

`wiom` is an acronym for `Who-Is-On-My-Wifi` and also a command line input. So please open cmd as administrator and run: `wiom -w -t 60`  here or open python using `python` (or `python3`) and type:
```python3
from who_is_on_my_wifi import *

WHO = who() # who(n)
for j in range(0, len(WHO)):
	comm = f"\n{WHO[j][0]} {WHO[j][1]}\n{WHO[j][2]} {WHO[j][3]}\n{WHO[j][4]} {WHO[j][5]}\n"
	print(comm)
```

[Here](https://github.com/tucnakomet1/Python-Who-Is-On-My-WiFi#usage) is an Usage part in README.md file.


I hope it helps! Please give me feedback.

**Comment by ehtesham-ali** [comment]
Ahhh I forgot to run the program as Admin.... that's why I was getting those errors! I ran `wiom -w -t 60` in the admin command prompt and all my devices are now showing. 

I should probably really read the documentation before asking for help haha, thanks for your help!
